version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
        postgres:
          condition: service_healthy
      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready --username "postgres" --dbname "postgres"
      interval: 1s
      retries: 5
      timeout: 5s
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate:4
    command: "-source 'file://migrations' -database 'postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable' up"
    depends_on:
      postgres:
        condition: service_healthy

    volumes:
      - ./migrations:/migrations:ro


  # adminer:
  #   image: adminer
  #   ports:
  #     - "8080:8080"